# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_github_packages:
  - RDocTaskForce/pkgcond

after_success:
  - Rscript -e 'covr::codecov()'